### ISSUE TITLE
Selectize JavaScript / CSS not included in build

### ISSUE THREAD

**Issue by green-arrow** [lifegadget/ui-selectize#1]
When installing the addon, the Selectize JS / CSS are not included in the Broccoli build. You have to manually add these files to get the component to work. I think that we would want to at least provide some defaults for the JS / CSS so that the developer can run `ember install:addon ui-selectize` and immediately start using it.

**Comment by yankeeinlondon** [comment]
Yes I agree. I think this is fixed now. Can you let me know if this is still a problem?

**Comment by green-arrow** [comment]
I do not see any updates to `index.js`, so I don't believe the issue is fixed. In your `index.js`, you would need something like this:

``` javascript
/* jshint node: true */
'use strict';

module.exports = {
  name: 'ui-selectize',
  included: function(app) {
    this._super.included(app);

    app.import(app.bowerDirectory + '/selectize/dist/js/standalone/selectize.js');
    app.import(app.bowerDirectory + '/selectize/dist/css/selectize.css');
  }
};
```

Since there are multiple possible CSS files, it may be nice to allow the user to manually override the decisions found in `index.js` by passing in an options hash to `new EmberApp()`. Does that make sense?

**Comment by yankeeinlondon** [comment]
Ahhh. I'm an idiot. It's all there but it's in the `addon` directory. Moving now.

**Comment by yankeeinlondon** [comment]
Ok. Seems to be fixed now in my app. Thanks for your patience.

**Comment by green-arrow** [comment]
I see it now, looks good!
