### ISSUE TITLE
Custom rendering

### ISSUE THREAD

**Issue by john-griffin** [lifegadget/ui-selectize#11]
Is there a way at the moment to hook into selectize custom rendering https://github.com/brianreavis/selectize.js/blob/master/docs/usage.md#rendering?

This would be useful, for example, if you wanted to include an image next to each item in the results dropdown.

**Comment by yankeeinlondon** [comment]
Yes in fact its on my TODO list for today although I suspect it may push a day or two.

**Comment by john-griffin** [comment]
Ah awesome, good timing :smile:

**Comment by yankeeinlondon** [comment]
Been trying to do this in an elegant way with inline block components but I think I just may revert to basic for now. Damn. :^/

**Comment by yankeeinlondon** [comment]
Ok, it's in for `0.2.1`
