### ISSUE TITLE
Value observing beyond init

### ISSUE THREAD

**Issue by john-griffin** [lifegadget/ui-selectize#12]
The selectize component can take an initial value array that renders correctly on first launch, this array is then updated when selecting items. However if that value array is modified outside of the component (e.g. a separate button with an action that tries to add an item to the value array) the changes do not propagate into the component and render because its maintaining its own internal value array.

Is there a way of making changes to the value array outside of the component so that the new items are reflected inside the selectize component?

**Comment by yankeeinlondon** [comment]
oh really. that's an oversight. should be pretty easy to fix.

**Comment by yankeeinlondon** [comment]
I just tried to reproduce this and couldn't. Can you give me an example? Maybe a twiddle?

**Comment by yankeeinlondon** [comment]
@john-griffin I'm going to close this but if you can re-create just re-open
