### ISSUE TITLE
Rendering an ember component

### ISSUE THREAD

**Issue by Ramblurr** [lifegadget/ui-selectize#14]
I would like to render a custom component for the "item"s in selectize. Currently using ui-selectize I have to return a string of html to be used to render the item.

Is there anyway to render an ember component here? And of course get the full benefit of a component with actions, etc?

**Comment by yankeeinlondon** [comment]
I think that would be ideal. I included the more cumbersome HTML string approach for now because it was easier but at some point I'd like move to this. In the mean time, however, I'd be happy to take a PR if you have the time.

**Comment by Ramblurr** [comment]
@ksnyde Thanks, I'll take a look at it.

A related question, whem you use the existing Renders, the `this` of the render callback function is selectize. Is there no way to use the render feature but retain access to the `this` of my Ember controller?

**Comment by yankeeinlondon** [comment]
Don't have much time today, but if I remember right there are examples in the codebase of where the callbacks are bound to the `this` scope of the Ember component.

**Comment by yankeeinlondon** [comment]
hi @Ramblurr, any progress?

**Comment by Ramblurr** [comment]
No, basically this is blocked by https://github.com/brianreavis/selectize.js/pull/617. Selectize has to allow us to return DOM / jquery elements rather than HTML strings.

**Comment by yankeeinlondon** [comment]
I see. Do you think using something like [wormhole](https://github.com/yapplabs/ember-wormhole) would be able to make this work in the interim?

**Comment by yankeeinlondon** [comment]
I think this underlying issue has now been fixed ... if you're still interested.

**Comment by yankeeinlondon** [comment]
I've got this working now if you're interested @Ramblurr

**Comment by Ramblurr** [comment]
Thanks @ksnyde! I'll check it out, but we're in the process of migrating away from selectize.js to [ember-power-select](http://ember-power-select.com/). It's much leaner than selectize, fully-emberfied, and much better for my sanity to develop against.

**Comment by yankeeinlondon** [comment]
Yeah I was just talking with Miguel about power-select and I think it hits all my use-cases too

**Comment by Ramblurr** [comment]
Many thanks for maintaining this project by the way, it was incredibly helpful.
