### ISSUE TITLE
onItem action not working in demo

### ISSUE THREAD

**Issue by stravid** [lifegadget/ui-selectize#16]
I discovered that your great online demo seems to be broken when it comes to the `onItem` action.

Looking [at the source code](https://github.com/lifegadget/ui-selectize/blob/5e493457731d75b9668d97f3ccf9d35c6f50ba2b/addon/mixins/api-surface.js#L161-L171) it seems the action names etc. are inconsistent with the rest.

Is this a bug or intentional?

**Comment by yankeeinlondon** [comment]
Not intentional. I can't look at this until later but can you give me a more a little more detail on what you tried and how you'd expected it to work. It's certainly possible that this area hasn't gotten enough testing yet.

**Comment by stravid** [comment]
If you go to http://development.ui-selectize.divshot.io/actions and select an option you will see that the `onOption` event is triggered but no `onItem` event. It is my understanding that an `onItem` event should have also been triggered.

Does this clear things up?

**Comment by yankeeinlondon** [comment]
should be fixed now in `0.2.7`

**Comment by yankeeinlondon** [comment]
note: divshot is having some issues so not yet on demo site but it should work
