### ISSUE TITLE
options with the first letter in uppercase

### ISSUE THREAD

**Issue by flaviooliveri** [lifegadget/ui-selectize#17]
When an option is added and the first letter is capital, the id of the generated option has the first letter in lowercase, is it correct? I mean, from this code

  var objectifyString = function objectifyString(thingy) {
    return typeOf(thingy) === 'string' ? { id: camelize(thingy), name: thingy } : thingy;
  };

an option like "ANICEOPTION" will be added as { id: "aNICEOPTION", name: "ANICEOPTION"} 

After this, when items that already exists are added in the initailization, the items are not found in the options and the items are not added to the component.

I hope I was clear.

Cheers.

**Comment by yankeeinlondon** [comment]
This is the correct behaviour. If you only pass in a CSV string it will "camelize" the "id" and leave the "name" unchanged. If you instead want to be explicit about the "id" then you will need to pass in an array of string (or a ember-data result set). For instance:

```
 options = [
      {id: "ANICE", name: "Anice Option"},
      { etc ... }
 ]
```

**Comment by yankeeinlondon** [comment]
Please close this issue if that makes sense, if not please elaborate on your question.

**Comment by flaviooliveri** [comment]
Ok, I got it. Thanks.
