### ISSUE TITLE
camalCasing the data.

### ISSUE THREAD

**Issue by koryteg** [lifegadget/ui-selectize#18]
I would like the data I set to not be manipulated when it comes back. right now "this fancy tag" comes back as "thisFancyTag". I would like it to come back the same way I sent it in.

**Comment by yankeeinlondon** [comment]
The idea behind this was that you could quickly give a friendly "label" and it would auto-generate a more programatic "value". You _can_ do this now if you pass in a hash like: 

```
{ value: 'this fancy tag', label: 'this fancy tag' }
```

If you're defining your option values in the template then this doesn't really work though. In other components I've done more recently I've allowed a literal override such as:

```
{{ui-selectize options='this fancy tag,this plain tag::this plain tag' }}
```

this would work as it does for the _fancy_ tag and allow you to be _explicit_ if you want to be. Do you need a template solution?

**Comment by yankeeinlondon** [comment]
I'm going to close this for now but reopen it if you are still needing something.

**Comment by koryteg** [comment]
sorry it has been a busy week. I just tried formatting the tags like the above examples and was not able to get them to work correctly.
