### ISSUE TITLE
onItem action: 'remove' event not returning the item removed

### ISSUE THREAD

**Issue by Ramblurr** [lifegadget/ui-selectize#19]
the _onItemRemove handler is firing with a value of `null`. This is what I get:

``` js
Object {
  action: "remove",
  message: "removed 81 from the list",
  value: null,
  component: Class
}
```

There's no way to know which item was removed, unless I parse the message, which isn't the intention, I hope.

From : line 170 in api-surface.js

``` js
    _onItemRemove:function(value) {
      this.sendAction('onItem', {
        action:'remove',
        message: `removed ${value} from the list`,
        value: get(this,'value'),
        component: this
      });
    },
```

**Comment by Ramblurr** [comment]
seems to me that the `value:` line should read:

``` js
  value: value
```

Thoughts? Workarounds?

**Comment by yankeeinlondon** [comment]
I'll have a look at it over the weekend but if you want to put together a PR that's fine too

**Comment by Ramblurr** [comment]
@ksnyde  Ok, I see what the intention is now.

The `value: get(this,'value'),` means "all the currently selected items". I'm getting `null` because I only had one item in the list, and then I removed it.

Instead of returning the remaining items, I think it should return the item that was removed, as that's what the corresponding selectize.js event returns. 

Thoughts?

**Comment by yankeeinlondon** [comment]
@Ramblurr sorry I'm trying hard to stay in a no-distraction zone this week. I just checked the demo and it appears to work correctly. Try and work it out and if you're still having problems you can ping me here with more context.

**Comment by yankeeinlondon** [comment]
I just realised you might be getting tripped on the fact that `get` is defined as a `const` at the top of the file. It is in fact equivalent to `Ember.get(this, 'value')` which is a more defensive way of programming `this.get('value')`

**Comment by Ramblurr** [comment]
Yup, I realize that `get(this, value)` is doing `Ember.get()`. My question, is should it be doing that?

In the scope of the `_onItemRemove` function
- `get(this, value)` is a list containing all the selected items, **without** the item that has been removed
- `value` is the item that has been removed

Now my code, using ui-selectize, is listening to the Remove event and wants to know which item has been removed. But currently it's just passing back a list of all the elements currently selected, and I have no way to know which one is removed unless I maintain my own list and diff against it.

The fix would be [this here](https://github.com/Ramblurr/ui-selectize/commit/8bd6f02f2d7c9e80c2d9d3b79dda2dbf65fa3362)

The selectize.js remove event passes the item removed, so  I think ui-selectize should also.

**Comment by yankeeinlondon** [comment]
Yeah looking at it today I would agree with you. Can you make that change and send me a PR. I'll get it approved immediately.
