### ISSUE TITLE
Component cleanup causes error

### ISSUE THREAD

**Issue by green-arrow** [lifegadget/ui-selectize#2]
In `addon/components/ui-selectize.js`, the last method is titled `cleanup`:

``` javascript
cleanup: function() {
    this.get('selectize').off('initialize').off('optionAdd').off('change').off('dropdownOpen').off('dropdownClose').off('itemAdd').off('itemRemove');
}.on('willDestroyElement')
```

This method fails, because the `off` method does not support chaining. In looking at the source for the `off` event, it seems that you could rewrite the method above to just one call to `off` with no parameters, and achieve the same result:

``` javascript
cleanup: function() {
    this.get('selectize').off();
}.on('willDestroyElement')
```

**Comment by yankeeinlondon** [comment]
Thanks. I'll switch to the singular call to `off()` as you suggest. New release in the next hour.

**Comment by yankeeinlondon** [comment]
This is fixed. Let me know if you have any issues.
