### ISSUE TITLE
Action onType

### ISSUE THREAD

**Issue by juliankmazo** [lifegadget/ui-selectize#6]
Hi.

I want to use the action onType for loading new options. But is not working, or is not define. Can you helpme?

```
{{ui-tags-input options=locations value=cvcId placeholder='Ex: São Paulo' maxItems=1 labelField='name' valueField='cvcid' onType='searchLocations'}}
```

**Comment by yankeeinlondon** [comment]
The events being handled can be found here:

https://github.com/lifegadget/ui-selectize/blob/master/addon/components/ui-selectize.js#L159-L167

To understand the precise behaviours of these events just look in the selectize documentation. Hope this helps.

**Comment by yankeeinlondon** [comment]
I'm going to close this for now but please re-open or drop a PR if you continue to struggle with this issue.
