### ISSUE TITLE
install errors.

### ISSUE THREAD

**Issue by koryteg** [lifegadget/ui-selectize#7]
I needed to add `"selectize": "~0.12.1"` to my `bower.json` file in order to build. you should add this to the install docs or fix the dependency to be included in the original install.

**Comment by yankeeinlondon** [comment]
Did you install it via the `ember install ui-selectize` command or with `npm install ui-selectize`? The ember install should automatically run the [blueprint](https://github.com/lifegadget/ui-selectize/blob/master/blueprints/ui-selectize/index.js#L10-L12) which installs the bower dependency.

**Comment by yankeeinlondon** [comment]
any update on this?

**Comment by koryteg** [comment]
I have not tried again. but when i originally installed I did do `ember install ui-selectize`.

**Comment by yankeeinlondon** [comment]
were you developing an addon or app?

**Comment by koryteg** [comment]
an app.

**Comment by yankeeinlondon** [comment]
hmmm. ok strange. I'll keep this open for now. hopefully can carve out some time to investigate in the next week or so.

**Comment by yankeeinlondon** [comment]
finally got around to fixing this
