### ISSUE TITLE
Updated version 0.0.17 to 0.1.2

### ISSUE THREAD

**Issue by fbaraujo** [lifegadget/ui-selectize#9]
Hi Ken Snyder,

I updated the version of ui-selectize in my Ember application and it's stop working.

In my controller I have:

sortOptions: [{label:'Maior Preço', value:'byHighestPrice'},
                {label:'Menor Preço', value:'byLowestPrice'},
                {label:'Nome do Hotel', value:'byName'},
                {label:'Recomendados', value:'byRecommendation'}],
sort: 'byRecommendation'

And in template:

{{ui-select-input options=sortOptions value=sort class='form-control' placeholder="Ordenar por"}}

Can you help me?

**Comment by yankeeinlondon** [comment]
I would need a [twiddle](http://ember-twiddle.com/) or some other environment where this can be reproduced to understand this problem more. 

> Side note, but you should _not_ need to include 'form-control' as a class. All styling is already taken care of.

**Comment by fbaraujo** [comment]
Actually, in my template I have:

<pre>{{ui-select-input options=sortOptions value=sort labelField='label' valueField='value' placeholder="Ordenar por"}}</pre>

I don't know how to import your plugin in a twiddle. :(

Here are my package.json and bower.json, I don't know if it helps.

<b>package.json</b>

<pre>{
  "name": "my-portal",
  "version": "0.0.0",
  "description": "Small description for my portal goes here",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^2.1.2",
    "ember-browserify": "^1.0.1",
    "ember-cli": "1.13.8",
    "ember-cli-app-version": "1.0.0",
    "ember-cli-babel": "^5.1.3",
    "ember-cli-bootstrap-datepicker": "0.5.4",
    "ember-cli-dependency-checker": "^1.0.1",
    "ember-cli-full-calendar": "0.0.9",
    "ember-cli-htmlbars": "0.7.9",
    "ember-cli-htmlbars-inline-precompile": "^0.2.0",
    "ember-cli-ic-ajax": "0.2.1",
    "ember-cli-inject-live-reload": "^1.3.1",
    "ember-cli-less": "1.3.3",
    "ember-cli-moment-shim": "0.6.0",
    "ember-cli-nouislider": "0.7.0",
    "ember-cli-qunit": "^1.0.0",
    "ember-cli-release": "0.2.6",
    "ember-cli-selectize": "miguelcobain/ember-cli-selectize#optgroups",
    "ember-cli-sri": "^1.0.3",
    "ember-cli-sticky": "0.3.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-crumbly": "0.2.0",
    "ember-data": "1.13.5",
    "ember-data-filter": "1.13.0",
    "ember-disable-proxy-controllers": "^1.0.0",
    "ember-export-application-global": "^1.0.3",
    "ember-google-map": "0.0.23",
    "ember-inputmask": "0.2.0",
    "ember-moment": "3.6.2",
    "ember-radio-button": "1.0.7",
    "ivy-tabs": "git://github.com/IvyApp/ivy-tabs",
    "lodash": "^3.10.0",
    "moment": "^2.10.3",
    "pagination-pager": "2.1.1",
    "sweetalert": "^1.0.1",
    "ui-selectize": "0.1.2"
  }
}
</pre>

<b>bower.json</b>

<pre>{
  "name": "my-portal",
  "dependencies": {
    "ember": "1.12.1",
    "ember-cli-shims": "ember-cli/ember-cli-shims#0.0.3",
    "ember-cli-test-loader": "ember-cli-test-loader#0.1.3",
    "ember-data": "1.13.5",
    "ember-load-initializers": "ember-cli/ember-load-initializers#0.1.5",
    "ember-qunit": "0.4.9",
    "ember-qunit-notifications": "0.0.7",
    "ember-resolver": "~0.1.18",
    "jquery": "^1.11.3",
    "loader.js": "ember-cli/loader.js#3.2.1",
    "qunit": "~1.18.0",
    "bootstrap": "~3.3.5",
    "fontawesome": "~4.3.0",
    "selectize": "~0.12.1",
    "bootstrap-datepicker": "~1.4.0",
    "nouislider": "^8.0.1",
    "sticky": "~1.0.1",
    "moment-timezone": ">= 0.1.0",
    "moment": ">= 2.8.0",
    "fullcalendar": "~2.3.2",
    "momentjs": "~2.10.6",
    "jquery.inputmask": "3.1.49"
  }
}
</pre>

**Comment by yankeeinlondon** [comment]
When you say it "doesn't work" can you be more specific? What JS errors are there? What do you see? What do you not see? I think without being able to recreate the problem it will be hard for me to help.

**Comment by yankeeinlondon** [comment]
I'm going to close this for now but please reopen it if you can make it reproducible and I'm happy to take a look.
